version: '3.7'

services:
    web:
        build: .
        depends_on:
            - db
            - redis
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./django-app:/usr/src/app
        ports:
            - 8000:8000
            - 8888:8888
        env_file:
            - ./env.dev

    worker:
        build: .
        depends_on:
            - db
            - redis
            - web
        command: python manage.py qcluster
        volumes:
            - ./django-app:/usr/src/app
        env_file:
            - ./env.dev

    db:
        image: postgres:12.0-alpine
        volumes:
            - db_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=app-db

    minio:
        image: minio/minio
        command: server /data
        volumes:
            - minio_data:/data
        ports:
            - 9000:9000
        environment:
            - MINIO_ACCESS_KEY=MINIOACCESS
            - MINIO_SECRET_KEY=MINIOACCESSSECRET

    redis:
        image: redis:alpine

    mail:
        image: reachfive/fake-smtp-server
        ports:
            - 1080:1080
        
volumes:
    db_data:
    minio_data:
